//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ResourceMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ResourceMgr), typeof(SingletonManager<ResourceMgr>));
		L.RegFunction("InitNecessaryAsset", InitNecessaryAsset);
		L.RegFunction("LoadAssetFromAssetBundleSync", LoadAssetFromAssetBundleSync);
		L.RegFunction("LoadAssetFromAssetBundleAsync", LoadAssetFromAssetBundleAsync);
		L.RegFunction("New", _CreateResourceMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateResourceMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ResourceMgr obj = new ResourceMgr();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ResourceMgr.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitNecessaryAsset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ResourceMgr obj = (ResourceMgr)ToLua.CheckObject<ResourceMgr>(L, 1);
			obj.InitNecessaryAsset();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadAssetFromAssetBundleSync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ResourceMgr obj = (ResourceMgr)ToLua.CheckObject<ResourceMgr>(L, 1);
			AssetType arg0 = (AssetType)ToLua.CheckObject(L, 2, typeof(AssetType));
			string arg1 = ToLua.CheckString(L, 3);
			UnityEngine.Object o = obj.LoadAssetFromAssetBundleSync(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadAssetFromAssetBundleAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			ResourceMgr obj = (ResourceMgr)ToLua.CheckObject<ResourceMgr>(L, 1);
			AssetType arg0 = (AssetType)ToLua.CheckObject(L, 2, typeof(AssetType));
			string arg1 = ToLua.CheckString(L, 3);
			System.Action<UnityEngine.Object> arg2 = (System.Action<UnityEngine.Object>)ToLua.CheckDelegate<System.Action<UnityEngine.Object>>(L, 4);
			System.Action<float> arg3 = (System.Action<float>)ToLua.CheckDelegate<System.Action<float>>(L, 5);
			System.Collections.IEnumerator o = obj.LoadAssetFromAssetBundleAsync(arg0, arg1, arg2, arg3);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

