//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SingletonManager_ResourceMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SingletonManager<ResourceMgr>), typeof(System.Object), "SingletonManager_ResourceMgr");
		L.RegFunction("Init", Init);
		L.RegFunction("OnDestroy", OnDestroy);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SingletonManager<ResourceMgr> obj = (SingletonManager<ResourceMgr>)ToLua.CheckObject<SingletonManager<ResourceMgr>>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDestroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SingletonManager<ResourceMgr> obj = (SingletonManager<ResourceMgr>)ToLua.CheckObject<SingletonManager<ResourceMgr>>(L, 1);
			obj.OnDestroy();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, SingletonManager<ResourceMgr>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

